name: Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: check out code
        uses: actions/checkout@v4

      - name: build app
        run: ./scripts/buildprod.sh

