name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: testing
        run: go test -cover

      - name: set up gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: run gosec
        run: gosec ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4
      
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: set up staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: stylecheck
        run:
          test -z $(go fmt ./...);

      - name: stylecheck2
        run: echo $?

      - name: format
        run: go fmt

      - name: staticcheck
        run: staticcheck ./...
        
     
     
          
